//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advantages
    {
        public int Id { get; set; }
        public bool isEnabled { get; set; }
        public string Name { get; set; }
        public Nullable<int> PointCost { get; set; }
        public string Discription { get; set; }
        public bool isPhysical { get; set; }
        public bool isMental { get; set; }
        public bool isSocial { get; set; }
        public bool isExotic { get; set; }
        public bool isSuperNatural { get; set; }
        public bool isMundane { get; set; }
        public string Limitation { get; set; }
        public Nullable<bool> RequirementSet { get; set; }
        public Nullable<bool> hasLevels { get; set; }
        public Nullable<bool> isCreationLocked { get; set; }
        public string Reference { get; set; }
    }
}
