//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aliens
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string HomePlanet { get; set; }
        public string chemicalBasis { get; set; }
        public string LandOrWater { get; set; }
        public string LandHabitat { get; set; }
        public string WaterHabitat { get; set; }
        public string TrophicDiet { get; set; }
        public string PrimaryLocomotion { get; set; }
        public string SecondaryLocomotion { get; set; }
        public Nullable<bool> hasSecondaryLocomotuib { get; set; }
        public Nullable<double> Gravity { get; set; }
        public string SizeClass { get; set; }
        public Nullable<double> Size { get; set; }
        public string Symmetry { get; set; }
        public Nullable<int> Sides { get; set; }
        public Nullable<int> LimbSegments { get; set; }
        public string Tail { get; set; }
        public Nullable<int> Manipulators { get; set; }
        public string Skeleton { get; set; }
        public string SkinClass { get; set; }
        public string Skin { get; set; }
        public string Breathing { get; set; }
        public string Temperatur { get; set; }
        public string Growth { get; set; }
        public string Sex { get; set; }
        public string Gestation { get; set; }
        public string Strategy { get; set; }
        public Nullable<int> OffspringCount { get; set; }
        public string PrimarySense { get; set; }
        public string Vision { get; set; }
        public string Hearing { get; set; }
        public string Touch { get; set; }
        public string TasteSmell { get; set; }
        public string Intelligence { get; set; }
        public Nullable<int> IntelligenceValue { get; set; }
        public string MatingBehaviour { get; set; }
        public string SocialOrganization { get; set; }
        public Nullable<int> SocialGroupSize { get; set; }
        public string Concentration { get; set; }
        public string Curiosity { get; set; }
        public string Egoism { get; set; }
        public string Empathy { get; set; }
        public string Gegariousness { get; set; }
        public string Imagination { get; set; }
        public string Chauvinism { get; set; }
        public string Suspicion { get; set; }
        public string Playfulness { get; set; }
    }
}
