//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characters
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PlayerName { get; set; }
        public int PlayerId { get; set; }
        public Nullable<int> PointTotal { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> SizeModifier { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> UnspendPoints { get; set; }
        public string Appearance { get; set; }
        public Nullable<int> Strenght { get; set; }
        public Nullable<int> Dexterity { get; set; }
        public Nullable<int> Intelligence { get; set; }
        public Nullable<int> Health { get; set; }
        public Nullable<int> HitPoints { get; set; }
        public Nullable<int> WillPower { get; set; }
        public Nullable<int> Perception { get; set; }
        public Nullable<int> BasicLift { get; set; }
        public Nullable<int> BasicSpeed { get; set; }
        public Nullable<int> BasicMove { get; set; }
        public Nullable<int> PersonalTechnologyLevel { get; set; }
        public Nullable<int> ParryValue { get; set; }
    }
}
