//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disadvantages
    {
        public int Id { get; set; }
        public bool isEnabled { get; set; }
        public string Name { get; set; }
        public Nullable<int> PointCost { get; set; }
        public string Discription { get; set; }
    }
}
