//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class encycloPlanets
    {
        public int Id { get; set; }
        public Nullable<int> EncyclopediaId { get; set; }
        public string PlanetName { get; set; }
        public string PlanetDiscription { get; set; }
    }
}
