//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class encycloPerson
    {
        public int Id { get; set; }
        public Nullable<int> EncyclopediaID { get; set; }
        public string PersonName { get; set; }
        public string PersonDiscription { get; set; }
        public Nullable<int> PersonFactionId { get; set; }
        public string PersonFactionRank { get; set; }
    }
}
