//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactionTags
    {
        public int Id { get; set; }
        public int FactionId { get; set; }
        public string TagName { get; set; }
        public string Discription { get; set; }
        public string Effect { get; set; }
    }
}
