//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factions
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string HomePlanet { get; set; }
        public string Race { get; set; }
        public Nullable<int> Force { get; set; }
        public Nullable<int> Cunning { get; set; }
        public Nullable<int> Wealth { get; set; }
        public Nullable<int> CurrentHp { get; set; }
        public Nullable<int> MaxHp { get; set; }
        public Nullable<int> Income { get; set; }
        public Nullable<int> CurrectFacCreds { get; set; }
        public Nullable<int> Exp { get; set; }
        public Nullable<int> RelationShip { get; set; }
    }
}
