//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modifier
    {
        public int Id { get; set; }
        public string Group { get; set; }
        public string SubGroup { get; set; }
        public string Modifying_Property { get; set; }
        public string Modifying_Value { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string Description { get; set; }
        public string Operator { get; set; }
    }
}
