//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planets()
        {
            this.InnerMoonlets1 = new HashSet<InnerMoonlets>();
            this.MajorMoons1 = new HashSet<MajorMoons>();
            this.OuterMoonlets1 = new HashSet<OuterMoonlets>();
        }
    
        public int Id { get; set; }
        public int StarID { get; set; }
        public Nullable<int> SatelliteSize { get; set; }
        public Nullable<int> SatelliteType { get; set; }
        public Nullable<int> atmCate { get; set; }
        public Nullable<double> atmMass { get; set; }
        public string atmPres { get; set; }
        public Nullable<double> axialTilt { get; set; }
        public Nullable<int> baseType { get; set; }
        public Nullable<double> blackbodyTemp { get; set; }
        public Nullable<int> dayFaceMod { get; set; }
        public Nullable<double> density { get; set; }
        public Nullable<double> diameter { get; set; }
        public Nullable<double> gravity { get; set; }
        public string hydCoverage { get; set; }
        public Nullable<int> innerMoonlets { get; set; }
        public Nullable<bool> isResonant { get; set; }
        public Nullable<bool> isTideLocked { get; set; }
        public Nullable<int> majorMoons { get; set; }
        public Nullable<double> mass { get; set; }
        public Nullable<int> masterOrderID { get; set; }
        public Nullable<double> moonRadius { get; set; }
        public string name { get; set; }
        public Nullable<int> nightFaceMod { get; set; }
        public Nullable<double> orbitalCycle { get; set; }
        public Nullable<double> orbitalEccent { get; set; }
        public Nullable<double> orbitalPeriod { get; set; }
        public Nullable<double> orbitalRadius { get; set; }
        public Nullable<int> outerMoonlets { get; set; }
        public Nullable<double> parentDiam { get; set; }
        public Nullable<int> parentID { get; set; }
        public string parentName { get; set; }
        public Nullable<bool> retrogradeMotion { get; set; }
        public Nullable<double> rotationalPeriod { get; set; }
        public Nullable<int> selfID { get; set; }
        public Nullable<double> siderealPeriod { get; set; }
        public Nullable<double> surfaceTemp { get; set; }
        public Nullable<double> tecActivity { get; set; }
        public Nullable<double> tideForce { get; set; }
        public Nullable<double> tideTotal { get; set; }
        public Nullable<double> volActivity { get; set; }
        public string sattype { get; set; }
        public string atmnote { get; set; }
        public string RVM { get; set; }
        public string planetString { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InnerMoonlets> InnerMoonlets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MajorMoons> MajorMoons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OuterMoonlets> OuterMoonlets1 { get; set; }
        public virtual Stars Stars { get; set; }
    }
}
