//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirements
    {
        public int Id { get; set; }
        public string SourceType { get; set; }
        public Nullable<int> TargetRequirementID { get; set; }
        public Nullable<int> SourceItemID { get; set; }
        public string Condition { get; set; }
        public string TargetType { get; set; }
        public string SourceName { get; set; }
        public string TargetName { get; set; }
        public string ConditionValue { get; set; }
    }
}
