//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skills()
        {
            this.SkillSpecialization = new HashSet<SkillSpecialization>();
        }
    
        public int Id { get; set; }
        public string SkillName { get; set; }
        public string DifficultyLevel { get; set; }
        public string notes { get; set; }
        public Nullable<int> points { get; set; }
        public string reference { get; set; }
        public string specialization { get; set; }
        public string tech_level { get; set; }
        public string ControllingAttribute { get; set; }
        public string Description { get; set; }
        public string Modifiers { get; set; }
        public string Defaults { get; set; }
        public string Prerequisites { get; set; }
        public Nullable<bool> RequirementSet { get; set; }
        public bool isEnabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillSpecialization> SkillSpecialization { get; set; }
    }
}
