//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillSpecialization
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SkillId { get; set; }
        public string Default { get; set; }
        public string Discription { get; set; }
        public string Prerequisites { get; set; }
        public string Modifiers { get; set; }
        public Nullable<bool> IsOptional { get; set; }
    }
}
