//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public int Id { get; set; }
        public string SkillName { get; set; }
        public string DifficultyLevel { get; set; }
        public string notes { get; set; }
        public Nullable<int> points { get; set; }
        public string reference { get; set; }
        public string specialization { get; set; }
        public string tech_level { get; set; }
        public string ControllingAttribute { get; set; }
        public string Description { get; set; }
        public string Modifiers { get; set; }
    }
}
