//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class StarSystems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StarSystems()
        {
            this.Stars = new HashSet<Stars>();
        }
    
        public int Id { get; set; }
        public string sysName { get; set; }
        public Nullable<int> habitableZones { get; set; }
        public double maxMass { get; set; }
        public Nullable<int> numDwarfPlanets { get; set; }
        public Nullable<int> star2index { get; set; }
        public Nullable<int> star3index { get; set; }
        public Nullable<int> subCompanionStar2index { get; set; }
        public Nullable<int> subCompanionStar3index { get; set; }
        public double sysAge { get; set; }
        public int sysStars { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stars> Stars { get; set; }
    }
}
