//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stars()
        {
            this.Planets = new HashSet<Planets>();
        }
    
        public int Id { get; set; }
        public int SystemID { get; set; }
        public double currLumin { get; set; }
        public double distFromPrimary { get; set; }
        public double effTemp { get; set; }
        public Nullable<int> gasGiantFlag { get; set; }
        public double initLumin { get; set; }
        public double initMass { get; set; }
        public Nullable<bool> isFlareStar { get; set; }
        public string name { get; set; }
        public Nullable<double> orbitalEccent { get; set; }
        public Nullable<double> orbitalPeriod { get; set; }
        public Nullable<double> orbitalRadius { get; set; }
        public Nullable<double> orbitalSep { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<int> parentID { get; set; }
        public string parentName { get; set; }
        public double radius { get; set; }
        public Nullable<int> selfID { get; set; }
        public string specType { get; set; }
        public double starAge { get; set; }
        public string starColor { get; set; }
        public Nullable<int> sysPlanets { get; set; }
        public string StarOrder { get; set; }
        public string StellarEvolutionStage { get; set; }
        public string OrbitalDetails { get; set; }
        public string StarString { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planets> Planets { get; set; }
        public virtual StarSystems StarSystems { get; set; }
    }
}
