//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedModifier
    {
        public int Id { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<int> ForeignId { get; set; }
        public string Modi { get; set; }
        public Nullable<int> Value { get; set; }
        public string Operator { get; set; }
    }
}
