//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWNAdmin.Utility
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedMalus
    {
        public int Id { get; set; }
        public Nullable<int> AdvantageId { get; set; }
        public Nullable<int> DisadvantageId { get; set; }
        public Nullable<int> MalusId { get; set; }
    
        public virtual Advantages Advantages { get; set; }
        public virtual CharacterMalus CharacterMalus { get; set; }
        public virtual Disadvantages Disadvantages { get; set; }
    }
}
